on:
  workflow_dispatch:
permissions:
    actions: none
    attestations: none
    checks: none
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  release_when_tagged:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Debug
        run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: create pull request
        run: |
          RELEASE="$(date +'%Y.%m.%Y%m%d%H%I%S')"
          git checkout -b "release/$RELEASE"
          mkdir -p changelogs
          echo "## [$RELEASE] - " > "changelogs/$RELEASE.md"
          git add "changelogs"
          git commit -m "chore: release $RELEASE changelogs"
          git push --set-upstream origin "release/$RELEASE"
          gh pr create --base "${{ github.ref_name }}" --head "release/$RELEASE" --title "Release $RELEASE" --body "$RELEASE Triggered by ${{ github.workflow}} by @${{ github.triggering_actor }} for @${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
