on:
  workflow_dispatch:
permissions:
    actions: none
    attestations: none
    checks: none
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  release_when_tagged:
    runs-on: ubuntu-latest
    outputs:
      changed-directories: ${{ steps.create-pull-request.outputs.changed-directories }}
      release-branch: ${{ steps.create-pull-request.outputs.release-branch }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Debug
        run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
      - name: create pull request
        id: create-pull-request
        run: |
          RELEASE="$(date +'%Y.%m.%Y%m%d%H%I%S')"
          git config --local user.email "scottschreckengaust@users.noreply.github.com"
          git config --local user.name "Scott Schreckengaust"
          git checkout -b "release/$RELEASE"
          SINCE="$(gh release list --exclude-drafts --exclude-pre-releases --limit 1 --json tagName | jq -r '.[].tagName')"
          if [ -z "$SINCE" ]; then SINCE="$(git rev-list --max-parents=0 HEAD)"; fi;
          echo "$SINCE"
          CHANGEDFILES="$(git diff --name-only "$SINCE" HEAD | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')"
          SRCDIRECTORIES="$(echo $CHANGEDFILES | jq -r '.[] | select(. |startswith("src\/"))' | cut -d'/' -f2 | sort -u | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')"
          echo "changed-directories=$SRCDIRECTORIES" >> $GITHUB_OUTPUT
          mkdir -p changelogs
          echo "## [$RELEASE] - " > "changelogs/$RELEASE.md"
          echo "$SRCDIRECTORIES" >> "changelogs/$RELEASE.md"
          git add "changelogs"
          git commit -m "chore: release $RELEASE changelogs"
          git push --set-upstream origin "release/$RELEASE"
          gh pr create --base "${{ github.ref_name }}" --head "release/$RELEASE" --title "chore: release $RELEASE" --body "# $RELEASE triggered ${{ github.workflow}} by @${{ github.triggering_actor }} for @${{ github.actor }}"
          RELEASEBRANCH="release/$RELEASE"
          echo "release-branch=$RELEASEBRANCH" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  run_changed_files:
    if: ${{ needs.release_when_tagged.outputs.changed-directories != '[]' && needs.release_when_tagged.outputs.changed-directories != '' }}
    strategy:
      fail-fast: true
      matrix:
        changed-directory: ${{ fromJson(needs.release_when_tagged.outputs.changed-directories) }}
      max-parallel: 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [release_when_tagged]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: ${{ needs.release_when_tagged.outputs.release-branch }}
      - name: configure git
        run: |
          git config --local user.email "scottschreckengaust@users.noreply.github.com"
          git config --local user.name "Scott Schreckengaust"
          echo "::group::RUNNER object"
          echo "${{ toJson(runner) }}"
          echo "::endgroup::"
      - name: bump
        run: |
          echo "TODO: BUMP THE PACKAGE VERSION"
          echo "${{ github.run_id }}" >> "src/${{ matrix.changed-directory }}/__init__.py"
      - name: build
        run: |
          echo "TODO: BUILD THE DISTRIBUTION"
          mkdir -p "src/${{ matrix.changed-directory }}/dist/"
          echo "${{ matrix.changed-directory }}" > "src/${{ matrix.changed-directory }}/dist/${{ github.run_id }}"
      - name: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: package-${{ matrix.changed-directory }}
          path: src/${{ matrix.changed-directory }}/dist/
      - name: record
        run: |
          git add "src/${{ matrix.changed-directory }}"
          git commit -m "chore: add src/${{ matrix.changed-directory }}"
          git pull
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
