on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  tag_on_release_merge:
    if: github.event.pull_request.merged == true && startsWith( github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
      - uses: actions/checkout@v4
        with:
          ref: github.sha
      - name: Create Tag
        run: |
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
      - name: Push Tag
        run: git push origin "v${{ github.run_number }}"
