on:
  push:
    tags:     
      - '**'
permissions:
    actions: none
    attestations: none
    checks: none
    contents: none
    deployments: none
    discussions: none
    id-token: none
    issues: none
    models: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  release_when_tagged:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debug
        run: |
          echo "::group::GITHUB object"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN}}
        run: |
          VERSION="${{ github.run_number }}"
          gh release create "$VERSION" \
            --generate-notes \
            --draft \
            --verify-tag
          echo "# $VERSION" > RELEASE_NOTES.md
          gh release view "$VERSION" --json body | jq -r '.body' > GENERATED_NOTES.md
          cat RELEASE_NOTES.md GENERATED_NOTES.md | gh release edit "$VERSION" \
            --draft=false \
            --notes-file -
